platform :ios, '9.0'

target 'VFlyer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VFlyer
    #Facebook dependencies
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'

  target 'VFlyerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
